// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Psicowise.Infrastructure.Contexts;

#nullable disable

namespace Psicowise.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240622031606_PsicologoNuloFixed")]
    partial class PsicologoNuloFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Psicowise.Infrastructure.Models.PsicologoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agendas")
                        .HasColumnType("text");

                    b.Property<string>("Consultas")
                        .HasColumnType("text");

                    b.Property<string>("Crp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pacientes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Psicologos");
                });
#pragma warning restore 612, 618
        }
    }
}
